spring.application.name=dev
spring.datasource.url=jdbc:postgresql://localhost:5433/usuarios
spring.datasource.username=usuarios
spring.datasource.password=54321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
